FROM envoyproxy/envoy:v1.35.0

USER root

RUN mkdir -p /etc/envoy

RUN groupmod -g 1000 envoy && usermod -u 1000 -g 1000 envoy

USER 1000

EXPOSE 8080 8443

CMD ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
