{{/* Create a secret with self-signed certs only if we are using the minikube profile. */}}
{{- if eq .Values.profile "minikube" }}
apiVersion: v1
kind: Secret
metadata:
  name: envoy-mtls-secret
  namespace: default
type: Opaque
data:
  server.crt: {{ .Files.Get "certs/server.crt" | b64enc }}
  server.key: {{ .Files.Get "certs/server.key" | b64enc }}
  ca.crt: {{ .Files.Get "certs/ca.crt" | b64enc }}
{{- end }}