apiVersion: v1
kind: Pod
metadata:
  name: client-certs-curl-debug
spec:
  restartPolicy: Always
  containers:
    - name: curl-debug
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: client-certs
          mountPath: /etc/certs
          readOnly: true
  volumes:
    - name: client-certs
      secret:
        secretName: client-certs
