apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  restartPolicy: Always
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: curl-certs
          mountPath: /etc/certs
          readOnly: true
  volumes:
    - name: curl-certs
      secret:
        secretName: curl-certs
