# Default values for eric-oss-hello-world-python-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  timezone: UTC
  registry:
    url: armdocker.rnd.ericsson.se
    imagePullPolicy: Always
  pullSecret:
  internalIPFamily:

imageCredentials:
  repoPath:
  pullPolicy: IfNotPresent
  registry:
    url:
  pullSecret:

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

labels: {}

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

# choice='unconfined, runtime/default, localhost' [ default= ""]
# Configuration of AppArmor profile type. The following values are possible:
# unconfined  - Indicates that there is no profile loaded.
# runtime/default - Applies the default profile of the container engine.
# localhost   - Applies a specific profile loaded on the host
appArmorProfile:
  type: "RuntimeDefault"

seccompProfile:
  type: "RuntimeDefault"
  localhostProfile:

service:
  type: ClusterIP
  http-port: 8080
  https-port: 8443

resources:
  helloWorld:
    limits:
      cpu: "100m"
      memory: "64Mi"
    requests:
      cpu: "2m"
      memory: "4Mi"

nodeSelector:

tolerations:
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 0
  - key: node.kubernetes.io/unreachable
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 0

affinity: {}

env:
  # Tracing configuration
  jaeger:
    ## disabled, When true will disable Jaeger tracer, will use opentracing.NoopTrace, No context will propagate
    disabled: true
    ## tags, key value pairs. The tags will be applied to the tracer and will be shown in UI process section.
    ## Example: service=service-a, version=1.0.1
    tags:
    agent:
      host: eric-dst-agent
      port: 6831
    sampler:
      type: remote
      param: 1
      refreshInterval: 30s
    reporter:
      logSpans: true

prometheus:
  scrape: true
  path: "/sample-app/python/metrics"

terminationGracePeriodSeconds: 30

probes:
  eric-oss-hello-world-python-app:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
  proxy:
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10

# Pod priority configuration for deployments
podPriority:
  eric-oss-hello-world-python-app:
    priorityClassName : ""

# Defaults if these values are not provided at instantiation
instantiationDefaults:
  platformCaCertMountPath: "/etc/tls-ca/platform/"
  appCertMountPath: "/etc/tls/log/"
  clientCredsMountPath: "/etc/client-creds/"
  proxyCaCertMountPath: "/etc/certs/ca"
  proxyAppCertMountPath: "/etc/certs/app"

global:
  clientCredentials:
    secret:
      clientIdKey: "clientId"
      name: "<instance id>-cc"

#TODO: Verify if this is needed and update if needed
eic:
  namespace: "namespace"