apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eric-oss-hello-world-python-app.name" . }}
  labels:
    {{- include "eric-oss-hello-world-python-app.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations:
    {{- include "eric-oss-hello-world-python-app.product-info" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-hello-world-python-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if and (eq .Values.updateStrategy.type "RollingUpdate") .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
{{- if .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
{{- end }}
{{- if .Values.updateStrategy.rollingUpdate.maxSurge }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
{{- end }}
    {{- end }}
  template:
    metadata:
      labels:
        rapp-name: {{ include "eric-oss-hello-world-python-app.name" . }}
        app: {{ include "eric-oss-hello-world-python-app.name" . }}
        app.kubernetes.io/name: {{ include "eric-oss-hello-world-python-app.name" . }}
        app.kubernetes.io/version: {{ include "eric-oss-hello-world-python-app.version" . }}
        helm.sh/chart: {{ template "eric-oss-hello-world-python-app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        rapp.metrics/scraping: "true"
      annotations:
        {{- if not (semverCompare ">=1.30.0" .Capabilities.KubeVersion.GitVersion) }}
        container.apparmor.security.beta.kubernetes.io/eric-oss-hello-world-python-app: {{ include "eric-oss-hello-world-python-app.appArmorProfileAnnotation" . | default "runtime/default" }}
        {{- end }}
        prometheus.io/port: '{{ index .Values.service "https-port" }}'
        prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
        prometheus.io/path: "{{ .Values.prometheus.path }}"
{{- include "eric-oss-hello-world-python-app.product-info" . | indent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if (index .Values "podPriority" "eric-oss-hello-world-python-app" "priorityClassName") }}
      priorityClassName: {{ (index .Values "podPriority" "eric-oss-hello-world-python-app" "priorityClassName") }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "eric-oss-hello-world-python-app.name" . }}
            items:
              - key: LOG_CTRL_FILE
                path: logcontrol.json
        - name: envoy-config
          configMap:
            name: {{ include "eric-oss-hello-world-python-app.name" . }}-envoy-configmap
            items:
              - key: ENVOY_CONFIG_FILE
                path: envoy.yaml
        - name: platform-cacerts
          secret:
            secretName: {{ index .Values "platformCaCertSecretName" | quote }}
            defaultMode: 420
        - name: app-certs
          secret:
            secretName: {{ index .Values "appSecretName" | quote }}
            defaultMode: 420
        - name: client-creds
          secret:
            secretName: {{ include "eric-oss-hello-world-python-app.clientSecret" . | quote }}
            defaultMode: 420
        - name: proxy-platform-cacerts
          secret:
            secretName: {{ index .Values "platformCaCertSecretName" | quote }}
            defaultMode: 420
        - name: proxy-app-certs
          secret:
            secretName: {{ index .Values "appSecretName" | quote }}
            defaultMode: 420
      containers:
        - name: eric-oss-hello-world-python-app
          image: {{ template "eric-oss-hello-world-python-app.imagePath" (dict "imageId" "eric-oss-hello-world-python-app" "values" .Values "files" .Files) }}
          imagePullPolicy: {{ include "eric-oss-hello-world-python-app.registryImagePullPolicy" . | quote }}
          securityContext:
            {{- if semverCompare ">=1.30.0" .Capabilities.KubeVersion.GitVersion }}
            appArmorProfile:
              type: {{ include "eric-oss-hello-world-python-app.appArmorProfile.type" . | default "RuntimeDefault" }}
            {{- end }}
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
              - all
            {{- include "eric-oss-hello-world-python-app.seccomp-profile" . | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/adp
            - name: platform-cacerts
              mountPath: {{ index .Values "platformCaCertMountPath" | default .Values.instantiationDefaults.platformCaCertMountPath | quote }}
              readOnly: true
            - name: app-certs
              mountPath: {{ index .Values "appCertMountPath" | default .Values.instantiationDefaults.appCertMountPath | quote }}
              readOnly: true
            - name: client-creds
              mountPath: {{ index .Values "clientCredsMountPath" | default .Values.instantiationDefaults.clientCredsMountPath | quote }}
              readOnly: true
          env:
            - name: IAM_CLIENT_ID
              value: {{ index .Values "clientId" | quote }}
            - name: IAM_CLIENT_SECRET
              value: {{ index .Values "clientSecret" | quote }}
            - name: IAM_BASE_URL
              value: {{ index .Values "iamBaseUrl" | quote }}
            - name: LOG_ENDPOINT
              value: {{ index .Values "logEndpoint" | quote }}
            - name: CA_CERT_FILE_PATH
              value: {{ index .Values "platformCaCertMountPath" | default .Values.instantiationDefaults.platformCaCertMountPath | quote }}
            - name: CA_CERT_FILE_NAME
              value:  {{ index .Values "platformCaCertFileName" | quote }}
            - name: APP_KEY
              value: {{ index .Values "appKeyFileName" | quote }}
            - name: APP_CERT
              value: {{ index .Values "appCertFileName" | quote }}
            - name: APP_CERT_FILE_PATH
              value: {{ index .Values "appCertMountPath" | default .Values.instantiationDefaults.appCertMountPath | quote }}
            - name: CLIENT_CREDS_FILE_PATH
              value: {{ index .Values "clientCredsMountPath" | default .Values.instantiationDefaults.clientCredsMountPath | quote }}
            - name: CLIENT_ID_FILE_NAME
              value: {{ .Values.global.clientCredentials.secret.clientIdKey | quote }}
            - name: SERVICE_NAME
              value: {{ .Chart.Name }}
            - name: CONTAINER_NAME
              value: {{ .Chart.Name }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TZ
              value: {{ template "eric-oss-hello-world-python-app.timezone" . }}
            - name: LOG_CTRL_FILE
              value: "/etc/adp/logcontrol.json"
            {{- include "eric-oss-hello-world-python-app.jaegerEnv" . | indent 12 }}
          ports:
            - name: http-metrics
              containerPort: 8050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /sample-app/python/health
              port: 8050
          {{- if (index .Values "probes" "eric-oss-hello-world-python-app" "livenessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-hello-world-python-app" "livenessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-hello-world-python-app" "livenessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-hello-world-python-app" "livenessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-hello-world-python-app" "livenessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-hello-world-python-app" "livenessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-hello-world-python-app" "livenessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-hello-world-python-app" "livenessProbe" "timeoutSeconds") }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /sample-app/python/health
              port: 8050
          {{- if (index .Values "probes" "eric-oss-hello-world-python-app" "readinessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-hello-world-python-app" "readinessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-hello-world-python-app" "readinessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-hello-world-python-app" "readinessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-hello-world-python-app" "readinessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-hello-world-python-app" "readinessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "eric-oss-hello-world-python-app" "readinessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-hello-world-python-app" "readinessProbe" "timeoutSeconds") }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.helloWorld | nindent 12 }}
        - name: envoy-proxy
          image: {{ template "eric-oss-hello-world-python-app.imagePath" (dict "imageId" "eric-oss-hello-world-python-app-envoy" "values" .Values "files" .Files) }}
          imagePullPolicy: {{ include "eric-oss-hello-world-python-app.registryImagePullPolicy" . | quote }}
          securityContext:
            {{- if semverCompare ">=1.30.0" .Capabilities.KubeVersion.GitVersion }}
            appArmorProfile:
              type: {{ include "eric-oss-hello-world-python-app.appArmorProfile.type" . | default "RuntimeDefault" }}
            {{- end }}
            runAsUser: 60577
            runAsGroup: 60577
            fsGroup: 60577
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
              - all
            {{- include "eric-oss-hello-world-python-app.seccomp-profile" . | indent 12 }}
          command: ["envoy"]
          args: ["-c", "/etc/envoy/envoy.yaml", "--base-id", "1"]
          ports:
            - name: envoy-http
              containerPort: 8080
              protocol: TCP
            - name: envoy-https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8443
          {{- if (index .Values "probes" "proxy" "livenessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "proxy" "livenessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "proxy" "livenessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "proxy" "livenessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "proxy" "livenessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "proxy" "livenessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "proxy" "livenessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "proxy" "livenessProbe" "timeoutSeconds") }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: 8443
          {{- if (index .Values "probes" "proxy" "readinessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "proxy" "readinessProbe" "initialDelaySeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "proxy" "readinessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "proxy" "readinessProbe" "failureThreshold") }}
          {{- end }}
          {{- if (index .Values "probes" "proxy" "readinessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "proxy" "readinessProbe" "periodSeconds") }}
          {{- end }}
          {{- if (index .Values "probes" "proxy" "readinessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "proxy" "readinessProbe" "timeoutSeconds") }}
          {{- end }}
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
            - name: proxy-platform-cacerts
              mountPath: {{ index .Values "proxyCaCertMountPath" | default .Values.instantiationDefaults.proxyCaCertMountPath | quote }}
              readOnly: true
            - name: proxy-app-certs
              mountPath: {{ index .Values "proxyAppCertMountPath" | default .Values.instantiationDefaults.proxyAppCertMountPath | quote }}
              readOnly: true
      {{- if include "eric-oss-hello-world-python-app.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "eric-oss-hello-world-python-app.pullSecrets" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ include "eric-oss-hello-world-python-app.terminationGracePeriodSeconds" . }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- include "eric-oss-hello-world-python-app.tolerations" . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | indent 8 }}
      {{- end }}
      nodeSelector: {{ include "eric-oss-hello-world-python-app.nodeSelector" . | nindent 6 -}}
