{{- if .Values.ingress.enabled -}}
{{- $fullName := include "eric-oss-hello-world-python-app.name" . -}}
{{- $servicePort := .Values.service.port -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "eric-oss-hello-world-python-app.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  {{- with .Values.ingress }}
  annotations:
    {{- include "eric-oss-hello-world-python-app.product-info" . | indent 4 }}
    {{- if .annotations }}
      {{ .annotations | toYaml | indent 4 }}
    {{- end }}
    {{- if .ingressClass }}
      kubernetes.io/ingress.class: {{.ingressClass }}
    {{- end -}}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
{{- end }}
