name: Pylint and Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest-cov requests_mock pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test renaming script
        run: |
          echo "Setting permissions for script"
          chmod +x set_app_name.sh
          echo "Testing renaming script with invalid name (unsupported characters)"
          export APP_NAME="#INVALID"
          ! ./set_app_name.sh
          echo "Testing renaming script with invalid name (exceeding length)"
          export APP_NAME="this-app-has-a-name-that-exceeds-fifty-three-characters"
          ! ./set_app_name.sh
          echo "Testing renaming script with valid name"
          export APP_NAME="valid-app-name"
          ./set_app_name.sh

      - name: Pylint
        run: |
          pylint $(git ls-files '*.py')
      - name: Pytest
        run: |
          python3 -m pytest --cov=eric-oss-hello-world-python-app --cov-fail-under=90
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yaml

