name: Pylint and Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest-cov requests_mock pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Pytest
      run: |
        python3 -m pytest --cov=eric-oss-hello-world-python-app --cov-fail-under=100
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3.3.0
      with:
        files: .
        config_file: .markdownlint.yaml
